RequerimientosSPS/Controllers/SpsController.cs
using RequerimientosSPS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RequerimientosSPS.Controllers
{
    public class SpsController : Controller
    {
        private spsrequerimientosEntities db = new spsrequerimientosEntities();
        // GET: Sps
        public ActionResult Index()
        {
            var sps = db.sps.OrderByDescending(n => n.vuser).ToList();
            ViewBag.cumplidas = db.sps.Where(a => a.estadoSps.descripcion == "SPSCerrada").Count();
            ViewBag.pendientes = db.sps.Where(a => a.estadoSps.descripcion != "SPSCerrada").Count();
            return View(sps);
        }

        // GET: Sps/Details/5
        public ActionResult Details(int id)
        {
            var tarea = db.tarea.Where(n => n.sps.Id == id);
            return View(tarea);
        }

        // GET: Sps/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Sps/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sps/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Sps/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Sps/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Sps/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

RequerimientosSPS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Scripts/datatables/datatables.css")

    @Styles.Render("~/Content/select2/select2.css")
    @Styles.Render("~/Content/select2/select2-bootstrap.css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Requerimientos", "Index", "Sps", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Inicio", "Index", "Sps")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Styles.Render("~/Content/css")
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/Scripts/datatables/datatables.js")
    @Scripts.Render("~/Content/select2/select2.js")
    @Scripts.Render("~/Content/select2/select2_locale_es.js")
    @Scripts.Render("~/Scripts/requerimientos.js")
    @Scripts.Render("~/Scripts/buscador.js")
    @Scripts.Render("~/Scripts/moment.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.min.js")
</body>
</html>